### ISSUE TITLE
send函数bug提交

### ISSUE THREAD

**Issue by tomato-cc** [simplefeel/xhrfilter#2]
send: function(arg, xhr) {   
            var timeNow = Date.now();
            sendData = arg[0];
            if(!xhrTime[url]){
            // 第一次 该请求没有时间，需要新建
                xhrTime[url] = Date.now();
            }else{
            	// 判断是否在时间限定范围内，如果在范围内，则不请求
                if(timeNow - xhrTime[url] <= interval){
                  // 自注释这里代码，否则过期后一样判断为未过期
                 //   xhrTime[url] = Date.now();
                    return true
                }else{
                	// 超出锁定时间后，释放请求
                	xhrTime[url] = Date.now();
                }
            }

**Comment by simplefeel** [comment]
感谢，去抖这里逻辑是有点问题，另外，不考虑去抖的情况下，之前的代码取消掉的是上一次请求，释放的是当前请求，我重新修改了下，改成了取消当前请求，释放上一次请求。
